robot_radius: 0.6
inflation_radius: 0.8
obstacle_range: 10.0
raytrace_range: 10.0
observation_sources: base_lidar
base_lidar: {
    data_type: PointCloud2,
    topic: /robot0/points_raw, 
    min_obstacle_height: 0.0,
    max_obstacle_height: 2.0,
    marking: true, 
    clearing: true
}