global_costmap:
    global_frame: map
    robot_base_frame: robot0/base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    transform_tolerance: 1.0


    plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


    static_layer:
        enabled: true
        map_topic: /map                  # 确保与地图服务器的话题一致
    inflation_layer:
        enabled: true
        cost_scaling_factor: 3.0
        inflation_radius: 0.8