local_costmap:
  global_frame: robot0/odom
  robot_base_frame: robot0/base_link
  rolling_window: true
  width: 10.0
  height: 10.0
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 1.0


  plugins:
    - {name: local_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}

  local_obstacle_layer:
    enabled: true
    observation_sources: base_lidar
    base_lidar: {data_type: PointCloud2, topic: /robot0/points_raw, min_obstacle_height: 0.0, max_obstacle_height: 2.0, marking: true, clearing: true}

  local_inflation_layer:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 0.4
