controller_frequency: 10.0 #10.0 # 向底盘控制移动话题cmd_vel发送命令的频率，也是局部路径规划的更新频率，规划一次就算一次速度
controller_patience: 2.0 #5.0 # 在空间清理操作执行前，控制器花多长时间等有效控制下发

planner_frequency: 1.0 #1.0 # 全局规划操作的执行频率
planner_patience: 5.0 #7.0 # 在空间清理操作执行前，留给规划器多长时间来找出一条有效规划

base_local_planner: "teb_local_planner/TebLocalPlannerROS" # 指定用于move_base的局部规划器名称
base_global_planner: "global_planner/GlobalPlanner" #指定用于move_base的全局规划器插件名称